//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridViewEntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilce
    {
        public int IlceID { get; set; }
        public string IlceAdi { get; set; }
        public int IlceSehirID { get; set; }
    
        public virtual Sehir Sehir { get; set; }
    }
}
