//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridViewEntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public int KitapKategoriID { get; set; }
        public int KitapYili { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
